### b) Calculation of coefficients

In [2]:
from numpy.linalg import solve
import numpy as np

# Coefficients matrix for the system of equations
A = np.array([
    [1**3, 1**2, 1, 1],
    [2**3, 2**2, 2, 1],
    [3**3, 3**2, 3, 1],
    [4**3, 4**2, 4, 1]
])

# f(x) values (right-hand side of the equations)
b = np.array([0.5, 0.8, 0.9, 0.941176])

# Solve the system of linear equations for a, b, c, d
coefficients = solve(A, b)
coefficients

array([ 0.02352933, -0.241176  ,  0.85882267, -0.141176  ])

### b) Solving the cubic polynomial equation for f(x)=0.85 

In [3]:
# Adjust the polynomial to find the root for f(x) = 0.85
# Adjust the constant term in the coefficients array for the equation P(x) - 0.85 = 0
coefficients[3] -= 0.85

# Find the roots of the cubic polynomial P(x) - 0.85 = 0
roots = np.roots(coefficients)

# Filter real roots and consider only the ones within the range of the given data points
x_value_for_fx_085 = roots[np.isreal(roots)].real
x_value_for_fx_085

array([2.34546548])

### c) Calculation of coefficients

In [5]:
# Coefficients matrix for the system of equations (for quadratic interpolation)
A_quad = np.array([
    [0.5**2, 0.5, 1],
    [0.8**2, 0.8, 1],
    [0.9**2, 0.9, 1]
])

# x values (right-hand side of the equations)
b_quad = np.array([1, 2, 3])

# Solve the system of linear equations for a, b, c
coeffs_quad = solve(A_quad, b_quad)
coeffs_quad

array([ 16.66666667, -18.33333333,   6.        ])

### c) Solving the quadratic polynomial equation for f(x)=0.85 

In [8]:
# Substitute f(x) = 0.85 into the quadratic polynomial to find x
f_x = 0.85
x_value_for_fx_085_quad = coeffs_quad[0] * f_x**2 + coeffs_quad[1] * f_x + coeffs_quad[2]
x_value_for_fx_085_quad

2.458333333333334

### d) Calculation of coefficients

In [7]:
# Coefficients matrix for the system of equations (for cubic interpolation)
A_cubic = np.array([
    [0.5**3, 0.5**2, 0.5, 1],
    [0.8**3, 0.8**2, 0.8, 1],
    [0.9**3, 0.9**2, 0.9, 1],
    [0.941176**3, 0.941176**2, 0.941176, 1]
])

# x values (right-hand side of the equations)
b_cubic = np.array([1, 2, 3, 4])

# Solve the system of linear equations for a, b, c, d
coeffs_cubic = solve(A_cubic, b_cubic)
coeffs_cubic

array([ 191.59272681, -404.83733231,  282.46724775,  -62.97338165])

### d) Solving the quadratic polynomial equation for f(x)=0.85 

In [12]:
# Recalculating after code execution state reset
x_value = 191.59272681 * (0.85)**3 - 404.83733231 * (0.85)**2 + 282.46724775 * (0.85) - 62.97338165
x_value

2.2906896957162743

### d) Bisection Method

In [16]:
def f(x):
    return x**2 / (1 + x**2) - 0.85

# initializing variables for the bisection method with iteration tracking
a = 2
b = 3
iteration_count = 0
b = 3
tolerance = 1e-6
max_iterations = 100

# Bisection method with iteration tracking
for iteration_count in range(1, max_iterations + 1):
    m = (a + b) / 2  # Midpoint
    if abs(f(m)) < tolerance:
        break  # Solution found
    if f(a) * f(m) < 0:
        b = m
    else:
        a = m

# Solution and number of iterations
m, iteration_count

(2.3804779052734375, 16)